# Generated by Django 5.0.1 on 2026-07-24 05:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('config_file', models.CharField(max_length=255, verbose_name='Archivo de configuración')),
                ('scraper_type', models.CharField(choices=[('web', 'Web HTML'), ('api', 'API REST')], max_length=10, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('error', 'Error')], default='active', max_length=10, verbose_name='Estado')),
                ('requires_auth', models.BooleanField(default=False, verbose_name='Requiere autenticación')),
                ('uses_proxy', models.BooleanField(default=False, verbose_name='Usa proxy')),
                ('max_memory_mb', models.IntegerField(default=512, validators=[django.core.validators.MinValueValidator(128), django.core.validators.MaxValueValidator(2048)], verbose_name='RAM máxima (MB)')),
                ('timeout_seconds', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)], verbose_name='Timeout (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Configuración de Scraper',
                'verbose_name_plural': 'Configuraciones de Scrapers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('hourly', 'Cada hora'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('custom', 'Personalizado')], max_length=20, verbose_name='Frecuencia')),
                ('hour', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Hora')),
                ('minute', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Minuto')),
                ('day_of_week', models.CharField(blank=True, max_length=20, verbose_name='Día de la semana (0-6)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última ejecución')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Próxima ejecución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scrapers.scraperconfig', verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'Tarea Programada',
                'verbose_name_plural': 'Tareas Programadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScraperTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Programado')], default='manual', max_length=20, verbose_name='Tipo de ejecución')),
                ('rq_job_id', models.CharField(blank=True, max_length=100, verbose_name='ID de trabajo RQ')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalización')),
                ('items_scraped', models.IntegerField(default=0, verbose_name='Elementos extraídos')),
                ('errors_count', models.IntegerField(default=0, verbose_name='Errores')),
                ('log_file', models.CharField(blank=True, max_length=255, verbose_name='Archivo de log')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scrapers.scraperconfig', verbose_name='Configuración')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ejecutado por')),
            ],
            options={
                'verbose_name': 'Tarea de Scraper',
                'verbose_name_plural': 'Tareas de Scrapers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScraperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='Nivel')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scrapers.scrapertask', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Log de Scraper',
                'verbose_name_plural': 'Logs de Scrapers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='scrapers_sc_task_id_37d29a_idx'), models.Index(fields=['level', '-created_at'], name='scrapers_sc_level_c90f7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('data', models.JSONField(verbose_name='Datos')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='Extraído')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='scrapers.scraperconfig', verbose_name='Configuración')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='scrapers.scrapertask', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Dato Extraído',
                'verbose_name_plural': 'Datos Extraídos',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['config', '-scraped_at'], name='scrapers_sc_config__5fb89b_idx'), models.Index(fields=['task', '-scraped_at'], name='scrapers_sc_task_id_4c33ac_idx')],
            },
        ),
    ]
